#!/bin/sh /etc/rc.common

START=99
STOP=99

BEACON=`cat /sys/class/gpio/gpio24/value` # need to short to 3v3, because there is no pullup

start() {
if [ "$BEACON" = "1" ] ; then

if test -e /usr/bin/sx1276_test1_tx ; then
  logger "Start Beacon Transmitter"
  sx1276_test1_tx /dev/spidev0.1 > /tmp/beacontx.log 2>&1 &
fi

else

if test -e /usr/bin/broker_mqtts ; then
  logger "Start Broker"
  broker_mqtts /etc/sentrifarm-rsmb-config.txt > /tmp/broker.log 2>&1 &
fi

if test -e /usr/bin/sx1276_mqttsn_bridge ; then
  logger "Start Radio Relay in 5 seconds"
  sleep 5
  sx1276_mqttsn_bridge /dev/spidev0.1 connect 1883  > /tmp/relay.log 2>&1 &
fi

fi

}

stop() {
  killall sx1276_test1_rx
  killall sx1276_test1_tx
  killall sx1276_mqttsn_bridge
  killall broker_mqtts
}

